name: my_flutter_template
description: "Flutter structure template"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  form_validator:
    git: https://github.com/themisir/form-validator.git
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  skeletonizer: ^2.1.0+1
  freezed_annotation: ^3.1.0
  webview_flutter: ^4.13.0

  intl: any
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  dartz: ^0.10.1
  json_annotation: ^4.9.0
#  pretty_bloc_observer: ^1.0.4
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  freezed: ^3.1.0
  injectable: ^2.5.0
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  image_network: ^2.6.0
  pretty_dio_logger: ^1.4.0
  loading_indicator: ^3.1.1
  auto_route: ^10.1.0+1
  flutter_svg: ^2.2.0
  smooth_page_indicator: ^1.2.1
  pin_code_fields: ^8.0.1
  icons_plus: ^5.0.0
  google_maps_flutter: ^2.12.3
  map_location_picker: ^2.0.3
  toggle_switch: ^2.3.0
  qr_code_scanner: ^1.0.1
  scan: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner: ^2.5.4
  dependency_validator: ^5.0.2
  flutter_lints: ^6.0.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  awesome_snackbar_content:
    git:
      url: https://github.com/aleemElmozogi/awesome_snackbar_content.git
      ref: fix/bubble-icon-cropping
  auto_route_generator:
  flutter_form_builder: ^10.1.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
flutter_intl:
  enabled: true
